### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by icoluccio**
### Summary
Working right out of bootstrap.

### CODE REVIEW

**Review by zeminlu — APPROVED** [review]

**Review by zeminlu — CHANGES_REQUESTED** [review]
Thought it was ok, but just noticed that .idea/workspace.xml should be excluded from versioning.

**Comment by icoluccio** [comment]
Fixed that!

**Review by zeminlu — APPROVED** [review]
Great!
Just so you know, you can (and probably should) version the whole .idea folder as long as you ignore the .idea/workspace.xml... at least when working with other people in a team.

**Comment by icoluccio** [comment]
Hm but that would mean committing project configuration. Why would I, when people can use other IDEs? If that's the standard for the department I'll respect it though (and add it in a following PR)

**Pull request merged**
